# Spring config
server:
  port: 8081

  
spring:
  application:
    name: customer-svc
  jpa:
    hibernate:
      ddl-auto: update      
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/customers
    driverClassName: com.mysql.cj.jdbc.Driver
    username: customers_svc_user
    password: customers_svc_pass

eventuate:
  database:
    schema: customers

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092
  zookeeper:
    connection:
      string: localhost:2181

      
### App Logging
logging:
  pattern:
    console: '%clr(%d{HH:mm:ss.SSS}){white} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]){white}
      %clr(:){green} %clr(%m){faint}%n'
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        orm:
          jpa: INFO
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    io:
      eventuate: debug


management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
        





